version: "3.7"

services:
  yun-serve:
    container_name: yun-serve
    image: yun-serve
    environment:
      - DATABASE=db
      - USERNAME=user
      - PASSWORD=password
      - HOST=locashot
      - PORT=3306
    networks:
      - proxy

networks:
  proxy:
    external: true
