services:
  yun-serve:
    restart: always
    container_name: yun-serve
    image: registry.cn-shenzhen.aliyuncs.com/sliwei/yun-serve:${TAG}
    environment:
      - ENV=live
      - MODE=production
      - DATABASE=bdm296810572_db
      - USERNAME=admin
      - PASSWORD=lw555wam.
      - HOST=bstu.cn
      - PORT=3306
    networks:
      - proxy

networks:
  proxy:
    external: true